import image from "../assets/image/Wine.png";

export const productlist = [
  {
    id: 1,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 2,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 3,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 4,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 5,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 6,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 7,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
  {
    id: 8,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "3,600",
    bottle1: "50 bottles",
    remain: "14 ",
  },
];

export const wineCountry = [
  {
    id: 1,
    countryName: "Germany",
    regionName:'Jerome Galeyrand',
    regionName1:'Jérôme Galeyrand',
    regionName2:'Jérôme Galeyrand',
    regionName3:'Chandon de Briailles',
    regionName4:'Claude and François de Nicolay',
    regionName5:'Domaine Belle',
    regionName6:'Belle father and sons',
    explor:'Jerome Galeyrand',
    explor1:'Chandonde Briailles',
    explor2:'Domaine Belle',
  },
  {
    id: 2,
    countryName: "Italy",
    regionName:'Chandonde Briailles',
    regionName1:'Jérôme Galeyrand',
    regionName2:'Jérôme Galeyrand',
    regionName3:'Chandon de Briailles',
    regionName4:'Claude and François de Nicolay',
    regionName5:'Domaine Belle',
    regionName6:'Belle father and sons',
    explor:' Jerome Galeyrand',
    explor1:' Chandonde Briailles',
    explor2:' Domaine Belle'
  },
  {
    id: 3,
    countryName: "USA",
    regionName:'Jerome Galeyrand',
    regionName1:'Jérôme Galeyrand',
    regionName2:'Jérôme Galeyrand',
    regionName3:'Chandon de Briailles',
    regionName4:'Claude and François de Nicolay',
    regionName5:'Domaine Belle',
    regionName6:'Belle father and sons',
    explor:'Jerome Galeyrand',
    explor1:'Chandonde Briailles',
    explor2:'Domaine Belle',
  },
 
];
