import image from "../assets/image/Wine.png";

export const productlist = [
  {
    id: 1,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 2,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 3,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 4,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 5,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 6,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 7,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
  {
    id: 8,
    name: 'Brunello di Montalcino "Piaggione" | 2019',
    subtitle: "6 single bottles",
    imageSrc: image,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "€3,600",
    bottle1: "50 bottles",
    remain: "14 remaining",
  },
];
