import Header from '@/components/header/page';
import './globals.css';
import type { Metadata } from 'next'
import Footer from '@/components/footer/page';
import { Jost } from 'next/font/google'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
const inter = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: ' Vinesia Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header/>
        
        {children}
        <Footer/>
        </body>
    </html> 
  )
}
