"use client";
import Header from "@/components/header/page";
import "./globals.css";
// import type { Metadata } from "next";
import Footer from "@/components/footer/page";
import { Jost } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Provider } from "react-redux";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Jost({ subsets: ["latin"] });
import store from "@/redux/store";
import GroupOFModal from "@/components/modal/GroupOFModal";

// export const metadata: Metadata = {
//   title: " Vinesia Market",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      staleTime: 50 * 60 * 1000, // 5 Minuts
    },
  },
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Provider store={store}>
          <QueryClientProvider client={queryClient}>
            <Header />
            <GroupOFModal />
            {children}
            <Footer />
          </QueryClientProvider>
        </Provider>
      </body>
    </html>
  );
}
